/**
 * Application Constants
 * 
 * Centralized constants for ports, timeouts, URLs, and default values.
 * Used across dev-server, worker-telemetry-api, and spline-api.
 * 
 * @module lib/constants
 */

// ============================================================================
// Version Constants
// ============================================================================

/**
 * [@PRODUCTION] Version Constants
 * Auto-generated by version-manager.ts
 * DO NOT EDIT MANUALLY - Use `bun run version:patch|minor|major` to update
 */

// Read package.json version synchronously
import { readFileSync } from 'fs';
import { join } from 'path';

let packageVersion = '3.1.0';
let apiVersion = '1.6.0';

try {
  const packageJsonPath = join(process.cwd(), 'package.json');
  const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf-8'));
  packageVersion = packageJson?.version || '3.1.0';
  
  // API version is independent: 1.6.0 (can be updated separately via version-manager)
  // This matches the tension mapping API version
  apiVersion = '1.6.0';
} catch (error) {
  // Fallback to defaults if package.json can't be read
  // This is fine for runtime - version manager will update it
}

export const PACKAGE_VERSION = packageVersion;
export const API_VERSION = apiVersion;

// ============================================================================
// Port Configuration
// ============================================================================

/** Default port for dev server */
export const DEFAULT_PORT = 3002;

/** Port for worker telemetry API */
export const WORKER_API_PORT = 3000;

/** Port for spline API */
export const SPLINE_API_PORT = 3001;

// ============================================================================
// Timeout Configuration
// ============================================================================

/** Default idle timeout in seconds */
export const DEFAULT_IDLE_TIMEOUT = 120; // seconds

/** Worker API timeout in milliseconds */
export const WORKER_API_TIMEOUT = 500; // milliseconds

/** Worker API check timeout in milliseconds */
export const WORKER_API_CHECK_TIMEOUT = 1000; // milliseconds

// ============================================================================
// URLs & External Resources
// ============================================================================

/** Repository URL */
export const REPO_URL = 'https://github.com/brendadeeznuts1111/wncaab-perf-v3.1';

// ============================================================================
// Default Values
// ============================================================================

/** Default package information */
export interface PackageInfo {
  version?: string;
  name?: string;
  description?: string;
  author?: string;
  license?: string;
}

export const DEFAULT_PACKAGE_INFO: PackageInfo = {
  version: PACKAGE_VERSION,
  name: 'wncaab-perf-v3.1',
  description: 'WNCAAB Performance Metrics & Visualization',
  author: 'WNCAAB Syndicate',
  license: 'MIT',
};

// ============================================================================
// Server Configuration
// ============================================================================

/** Default server hostname */
export const DEFAULT_HOSTNAME = '0.0.0.0';

/** Server identifier for X-Server header */
export const SERVER_NAME = 'wncaab-dev-server';

